### ISSUE TITLE
Fontforge not starting at all in a KDE Plasma wayland session

### ISSUE THREAD

**Issue by callegar** [fontforge/fontforge#5368]
Trying to use fontforge on Manjaro linux, with a KDE plasma session on Wayland.

Fontforge cannot be started.

```fontforge
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20230101
 Based on sources from 2023-04-07 06:26 UTC-ML-D-GDK3.

(fontforge:37290): Gdk-WARNING **: 18:12:56.283: cannot open display:
```

The output above also reports the fontforge version.

### When reporting a bug/issue:
- [ ] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [ X Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by callegar** [comment]
Diagnosed: you need to unset `GDK_BACKEND` or set it to `x11` for fontforge to work.
If fontforge cannot deal with `GDK_BACKEND=wayland` probably it should ignore it rather than breaking.

**Comment by iorsh** [comment]
How do gimp or inkscape start at the same command prompt? I'm not sure whether applications or the window manager are in charge of `GDK_BACKEND` setting.

**Comment by callegar** [comment]
Gimp and inkscape start just fine with GDK_BACKEND set to wayland on my system. Xeyes suggests that gimp starts as an X11 application, while inkscape is wayland.

**Comment by C0rn3j** [comment]
Can confirm that the var breaks things.

I did not run into the problem though as I do not force set `GDK_BACKEND`, just randomly found this issue.

@callegar On kwin you can use kwin debug console to see what is X and what's Wayland.  
Your xeyes test was correct though.

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
Memory: 62.0 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X670 AORUS ELITE AX
```
